# -*- coding: utf-8 -*-
"""merge_weather_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLA6I908QZsw6Rx1ZW9hCGQRqSftFJmR
"""

import pandas as pd
import requests
from functools import reduce

jay_peak = pd.read_csv("https://raw.githubusercontent.com/nedcut/ML-final/cc092ce8980008db6dd3927d091b9cc74ce0edb9/data/raw/jay_peak_weather.csv", skiprows=3)
sugarbush = pd.read_csv("https://raw.githubusercontent.com/nedcut/ML-final/cc092ce8980008db6dd3927d091b9cc74ce0edb9/data/raw/sugarbush_weather.csv", skiprows=3)
killington = pd.read_csv("https://raw.githubusercontent.com/nedcut/ML-final/cc092ce8980008db6dd3927d091b9cc74ce0edb9/data/raw/killington_weather.csv", skiprows=3)
stowe = pd.read_csv("https://raw.githubusercontent.com/nedcut/ML-final/cc092ce8980008db6dd3927d091b9cc74ce0edb9/data/raw/stowe_weather.csv", skiprows=3)

data_frames = {
    "jay_peak": jay_peak,
    "sugarbush": sugarbush,
    "killington": killington,
    "stowe": stowe
    }

for name, df in data_frames.items():
  df.columns = (
    df.columns
    .str.lower()
    .str.replace(" ", "_")
    .str.replace(r"\(.*?\)", "", regex=True)  # remove units
    .str.replace(r"[^a-z0-9_]", "", regex=True)
    .str.replace("__", "_")
    .str.strip("_")
)
  df["time"] = pd.to_datetime(df["time"])
  df["location"] = name

#Taking the average between resorts
merged_resorts = pd.concat(data_frames.values(), ignore_index=True)
merged_resorts["day"] = merged_resorts["time"].dt.date
print(merged_resorts.columns)
merged_resorts = merged_resorts.groupby(["day", "location"]).agg({
    "temperature_2m": "mean",
    "relative_humidity_2m": "mean",
    "snow_depth": "mean",
    "wind_speed_10m": "mean",
    "rain": "sum",
    "snowfall": "sum"
}).reset_index()

avg_weather = (
    merged_resorts.groupby("day", as_index = False).mean(numeric_only=True)
)

#Taking the resort with the highest snowfall, in line with how grades are predicted
best_snow = (
    merged_resorts
    .assign(priority=(merged_resorts["location"] != "sugarbush"))
    .sort_values(["day", "snow_depth", "priority"], ascending=[True, False, True])
    .drop_duplicates("day")
)

best_snow = best_snow.drop(columns = "priority")

avg_weather.to_csv("avg_weather.csv")
best_snow.to_csv("best_snow.csv")